### PR TITLE
Add papers for binary data modelling.

### PR DESCRIPTION
**Pull request by aby0**

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
Thanks so much for your contribution! Regarding the misprint thing, we follow the US English conventions here: http://grammarist.com/spelling/model/

**Comment by aby0** [comment]
Thanks @vmarkovtsev I missed signing off for earlier commits, shall I revert commit messages and open a new PR?

**Comment by vmarkovtsev** [comment]
Whatever is easier for you. Can be [squashed](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) and then `git commit --amend --no-edit --signoff` too.

**Comment by vmarkovtsev** [comment]
Superseded by #26

**Pull request closed without merging**
