### PR TITLE
Add torchnet to the list.

### PR DESCRIPTION
**Pull request by Soundug**
Signed-off-by: Soundarya G <soundaryagsk@gmail.com>

### CODE REVIEW

**Comment by EgorBu** [comment]
Thank you for the contribution! Could you explain how it's related to ML on Source Code?

**Comment by Soundug** [comment]
@EgorBu Its a framework for PyTorch that provides set of abstractions encouraging modular programming and code re-use. Also provides dataloading, logging, visualization utilities.
But I think its not related as much to ML on Source Code, more of a tool to ease logging, training and loading.

**Comment by Soundug** [comment]
@EgorBu 
How about [pmd](https://github.com/pmd/pmd) which is a source code analyzer including copy-paste-detector for languages like Java, C#, C, C++, Javascript, Ruby, PHP and more.
[Cortex](https://github.com/originrose/cortex) - Neural networks, regression and feature learning in Clojure. 
An [example](https://github.com/originrose/cortex/blob/master/examples/mnist-classification/src/mnist_classification/core.clj) using Cortex.

**Comment by EgorBu** [comment]
`pmd` - I don't see any ML.
`Cortex` - general ML library.
No for both options.
I close this PR - if you will have any questions - you can comment here.

**Pull request closed without merging**
