### PR TITLE
Add BigCloneBench

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Please fill the `[ ]` with an `x` to make sure that you read and followed the checklist

- [x] This addition is about Machine Learning __on Code__ specifically. General links should be added to [Awesome Machine Learning](https://github.com/josephmisiti/awesome-machine-learning) instead.
- [x] I have checked that the proposed addition is not already in the awesome list.
- [x] I have signed-off my commits as detailed [here](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md).
- [x] The links follow the link template:

        * [Title](URL) - Description.
    or

        * [Title](URL) - Description [Code](link to code).
- [x] The addition is correctly classified as a paper, blog post, talk, software or dataset.
- [x] The commit message must start with a verb (`Add …`, `Deprecate …`) and end without a dot. For exemple:

        Deprecate Theano software

### CODE REVIEW

**Review by EgorBu — COMMENTED** [review]
The link is hanging forever :cry:

**Comment by vmarkovtsev** [comment]
@EgorBu Not for me.

**Comment by m09** [comment]
For me neither (loaded quite fast). No DCO though, if you have time to fix it @vmarkovtsev :)

**Comment by vmarkovtsev** [comment]
Done

**Review by m09 — APPROVED** [review]

**Comment by m09** [comment]
@EgorBu I'm merging since both @vmarkovtsev and I didn't have problems accessing it today, if it comes back during next PRs we'll switch to archive or find another workaround!

**Pull request merged**
