### PR TITLE
Add Research paper

### PR DESCRIPTION
**Pull request by hiiakku**
Signed-off-by: Akshat Agarwal akshatb55@gmail.com

### CODE REVIEW

**Comment by m09** [comment]
Thanks @hiiakku for this paper! I see that you signed-off in the PR description, but it's actually required in the commit if we want to be able to merge it. Can you correct this? (more details [here](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md)). Thanks again for your contribution :+1:

**Comment by hiiakku** [comment]
Hey @m09 , I can't find an option of signing-off my commit using the UI. Can you guide me to do the desired task.

**Comment by vcoisne** [comment]
@hiiakku check this out https://github.com/src-d/guide/blob/6933caf7ebc7b052c3a2185d50776bc0803d8482/developer-community/fix-DCO.md#L131

**Comment by EgorBu** [comment]
Abandoned PR.

**Comment by vmarkovtsev** [comment]
@hiiakku Thank you very much for your contribution. If you return back, please ping us and we will immediately reopen.

**Pull request closed without merging**
