### PR TITLE
Add 'Learning a Static Analyzer from Data' paper

### PR DESCRIPTION
**Pull request by bzz**
While visiting Zurich last week, stumbled up on a paper that seems relevant - "Learning a Static Analyzer from Data".

Not sure what is the best section to add it to.

### CODE REVIEW

**Comment by warenlg** [comment]
Thank you @bzz, we just largely studied the papers of ETH Zurich on learning rules to build a static analyzer https://src-d.slack.com/archives/C7USX021L/p1533054263000059 nice coordination.

They deserve a spot on the awesome list. However as you felt it, IMO it could not be added to the LM section as they oppose their approach to traditional language models saying that n-grams are about "making predictions about program elements based on a fixed set of relatively shallow features", assuming that same features should not be used for different set of predictions. I believe we should initiate a new category like DSL or Decision trees

**Comment by bzz** [comment]
Was confused by the title of the section that is `Source Code Analysis and LM`, as this fits source code analysis part.

>  I believe we should initiate a new category like DSL or Decision trees

👍 If everyone agrees, will be happy to add it a move it there. @EgorBu @vmarkovtsev please let us know!

**Comment by warenlg** [comment]
True, now that I have a better overview of research around MLonCode, I feel like this section SCA and LM needs refinement among others (because you can do SCA without using LM which is the case here)
I can propose such a refinement in further PRs if the team agrees.

**Comment by EgorBu** [comment]
Thanks for a nice article!
I think we can include this article https://github.com/src-d/awesome-machine-learning-on-source-code#program-repair-and-bug-detection - bug detection is one of the tasks for static code analysis.

**Review by EgorBu — COMMENTED** [review]
Sign-off required.

**Comment by bzz** [comment]
> program-repair-and-bug-detection 

sounds good to me, addressed in 978fb23. 

@warenlg @EgorBu it's ready for another pass.

**Review by vmarkovtsev — APPROVED** [review]

**Comment by vmarkovtsev** [comment]
Thank you Alex.

**Pull request merged**
