### PR TITLE
3 new code summarization papers

### PR DESCRIPTION
**Pull request by bdqnghi**

### CODE REVIEW

**Comment by bdqnghi** [comment]
Not sure why it keeps prompting the error The sign-off is missing, I appended the sign-off at the end of my commits already

**Comment by m09** [comment]
Hi @bdqnghi! I think it's because it looks for it in a separate line. Thanks for sharing those papers!

**Comment by m09** [comment]
BTW you can use `git commit --amend --signoff` so that git appends automatically a signoff to your previous commit (based on your configured git.user.name and git.user.email). Then you can push this edited commit with the `-f` option of push (`git push -f`)

**Comment by bdqnghi** [comment]
I see, fixed it :+1:

**Comment by m09** [comment]
Almost there! Now your signoff is present twice. If you want to edit it you can use once again `git commit --amend` to edit your commit message and then push (again with -f)

**Comment by bdqnghi** [comment]
Fixed it : )

**Review by m09 — APPROVED** [review]

**Comment by m09** [comment]
Thanks for the PR, it looks good to merge now :)

**Review by vmarkovtsev — APPROVED** [review]

**Pull request merged**
