### PR TITLE
Add three ACL 2018 papers.

### PR DESCRIPTION
**Pull request by ShilinHe**
Add three ACL 2018 papers that are about semantic parsing.
Signed-off-by: Shilin HE <selin.hsl@gmail.com>

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@ShilinHe Thank you very much for your contribution!

Unfortunately, there are merge conflicts. Besides, could you please add "Signed-off-by" to your commits, e.g. using an interactive git rebase.

**Comment by ShilinHe** [comment]
@vmarkovtsev I have tried the rebase but it failed. I added the signed-off-by in the commit abed45a, but it does not work.

**Comment by vmarkovtsev** [comment]
You need to add the same signature to the previous commit too :disappointed:

**Comment by ShilinHe** [comment]
Yes, you are right! Thanks a lot!

**Comment by vmarkovtsev** [comment]
@ShilinHe This may help you: https://github.com/src-d/guide/blob/828a3becc2d066cd7d309df27dc329420f6df115/developer-community/fix-DCO.md

**Pull request merged**
