### PR TITLE
Add "A Fast Unified Model for Parsing and Sentence Understanding".

### PR DESCRIPTION
**Pull request by m09**

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@m09 @EgorBu Are you sure we need the separate category?

**Comment by m09** [comment]
I think we do since the primary object this paper is applied on is not code (but sentences) so it wouldn't fit in any of the main categories and it also doesn't fit in the existing related research headers.

It maybe means that even though the paper is interesting we should not include it in this repo though.

**Comment by vmarkovtsev** [comment]
Yeah we should only place papers which analyze source code. Shall I close then?

**Comment by m09** [comment]
Sure.

**Comment by m09** [comment]
Actually it could fit in the section Neural Network Architectures and Algorithms. I see that there are approaches that are not applied to code in the papers there (https://arxiv.org/pdf/1609.01704.pdf). Thoughts @vmarkovtsev @EgorBu ? If it fits I'll commit the change in section so that you can merge.

**Comment by eiso** [comment]
As I mentioned yesterday to @m09 this could be in the Related Research section.

**Comment by m09** [comment]
My initial PR was already adding it to the related research section so it should LGTM

**Review by vmarkovtsev — APPROVED** [review]

**Pull request merged**
